# ---------BUILD STAGE ----------

FROM node:20 AS build
WORKDIR /app
COPY package*.json app.js ./
#COPY app.js ./
RUN npm install
COPY . .

# ------ RUNTIME STAGE --------

FROM node:20-alpine
WORKDIR /app

COPY --from=build /app /app

EXPOSE 8080

USER node

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD node -e "process.exit(0)"

CMD ["npm", "start"]

