# ---------BUILD STAGE ----------

FROM node:20 AS build
WORKDIR /app
COPY package*.json app.js ./
#COPY app.js ./
RUN npm install
COPY . .

# ------ RUNTIME STAGE --------

FROM node:20-alpine
WORKDIR /app

COPY --from=build /app /app

EXPOSE 8080

USER node

CMD ["npm", "start"]

