FROM node:20

WORKDIR /app

COPY app/package*.json ./

RUN npm install
COPY app/app.js ./app.js
COPY . .

EXPOSE 8080

USER node

HEALTHCHECK --interval=10s --timeout=3s --retries=3 CMD node health.js

CMD ["npm", "start"]
