pipeline {
  agent { label 'wsl-docker' }

  environment {
    API_IMAGE = 'ghcr.io/amine12344/mlop-test-api'
    FRONTEND_IMAGE = 'ghcr.io/amine12344/mlop-test-frontend'
    DEPLOY_BRANCH = 'feature/test-argo'
    VERSION = "sha-${GIT_COMMIT}"
    TAG_SUFFIX = "_withjenkins"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Verify Docker') {
      steps {
        sh '''
          set -eux
          docker version
          helm version
          yq --version
          git --version
          node --version
          npm --version
        '''
      }
    }

    stage('Free Test Port') {
      steps {
        sh '''
          set +e
          echo "Freeing port 3009 if in use..."
          fuser -k 3009/tcp || true
          set -e
        '''
      }
    }

    stage('API Smoke Tests') {
      steps {
        sh '''
          set -eux
          cd app
          npm install
          npm test
        '''
      }
    }

    stage('Frontend Static Tests') {
      steps {
        sh '''
          set -eux
          chmod +x frontend/test-frontend.sh
          ./frontend/test-frontend.sh
        '''
      }
    }

    stage('Helm Validation') {
      steps {
        sh '''
          set -eux
          helm lint helm/mlop-test
          helm template mlop-test helm/mlop-test -n mlop-test > /tmp/rendered.yaml
          test -s /tmp/rendered.yaml
          grep -q "kind: Deployment" /tmp/rendered.yaml
          grep -q "kind: Service" /tmp/rendered.yaml
        '''
      }
    }

    stage('Build Images') {
      steps {
        sh '''
          set -eux
          docker build -t ${API_IMAGE}:${VERSION}${TAG_SUFFIX} ./app
          docker build -t ${FRONTEND_IMAGE}:${VERSION}${TAG_SUFFIX} ./frontend
        '''
      }
    }

    stage('Container Smoke Tests') {
      steps {
        sh '''
          set -eux

          docker network create mlop-test-net || true
          docker rm -f test-api test-frontend >/dev/null 2>&1 || true

          docker run -d --name test-api --network mlop-test-net \
            -e PORT=8080 \
            -e DB_HOST=postgres \
            -e DB_PORT=5432 \
            -e DB_NAME=postgres \
            -e DB_USER=postgres \
            -e DB_PASSWORD=postgres \
            -e APP_VERSION=test-ci \
            -p 18080:8080 \
            ${API_IMAGE}:${VERSION}${TAG_SUFFIX}

          sleep 4
          curl -fsS http://localhost:18080/healthz
          curl -fsS http://localhost:18080/readyz || true
          curl -fsS http://localhost:18080/ | grep version

          docker run -d --name test-frontend -p 18081:80 \
            ${FRONTEND_IMAGE}:${VERSION}${TAG_SUFFIX}

          sleep 3
          docker ps -a
          docker logs test-frontend || true

          # Minimal validation only: image starts
          docker inspect test-frontend --format='{{.State.Running}}' | grep true

          docker rm -f test-api test-frontend
        '''
      }
    }

    stage('Login to GHCR') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'ghcr-creds', usernameVariable: 'GH_USER', passwordVariable: 'GH_PAT')]) {
          sh '''
            set -eux
            echo "$GH_PAT" | docker login ghcr.io -u "$GH_USER" --password-stdin
          '''
        }
      }
    }

    stage('Push Images') {
      steps {
        sh '''
          set -eux
          docker push ${API_IMAGE}:${VERSION}${TAG_SUFFIX}
          docker push ${FRONTEND_IMAGE}:${VERSION}${TAG_SUFFIX}
        '''
      }
    }

    stage('Update Helm Values') {
      steps {
        sh '''
          set -eux
          yq -i '.api.image.tag = strenv(VERSION) + strenv(TAG_SUFFIX)' helm/mlop-test/values.yaml
          yq -i '.frontend.image.tag = strenv(VERSION) + strenv(TAG_SUFFIX)' helm/mlop-test/values.yaml
        '''
      }
    }
  }

  post {
    always {
      sh '''
        set -eu

        mkdir -p reports

        cat > reports/demo-report.html <<EOF
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Jenkins Demo Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 30px; background: #f8fafc; color: #111827; }
    h1 { margin-bottom: 6px; }
    .sub { color: #6b7280; margin-bottom: 24px; }
    .card {
      background: white;
      border: 1px solid #e5e7eb;
      border-radius: 12px;
      padding: 16px;
      margin-bottom: 16px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.04);
    }
    .label {
      font-weight: bold;
      color: #374151;
      display: inline-block;
      min-width: 150px;
    }
    code {
      background: #f3f4f6;
      padding: 2px 6px;
      border-radius: 6px;
      word-break: break-all;
    }
  </style>
</head>
<body>
  <h1>MLOps Demo Report</h1>
  <div class="sub">Generated by Jenkins pipeline</div>

  <div class="card">
    <div><span class="label">Branch:</span> <code>$DEPLOY_BRANCH</code></div>
    <div><span class="label">Commit:</span> <code>$GIT_COMMIT</code></div>
    <div><span class="label">Version Tag:</span> <code>$VERSION$TAG_SUFFIX</code></div>
    <div><span class="label">Build Number:</span> <code>$BUILD_NUMBER</code></div>
    <div><span class="label">Build URL:</span> <code>$BUILD_URL</code></div>
  </div>

  <div class="card">
    <div><span class="label">API Image:</span> <code>$API_IMAGE:$VERSION$TAG_SUFFIX</code></div>
    <div><span class="label">Frontend Image:</span> <code>$FRONTEND_IMAGE:$VERSION$TAG_SUFFIX</code></div>
  </div>
</body>
</html>
EOF

        docker rm -f test-api test-frontend >/dev/null 2>&1 || true
      '''
      archiveArtifacts artifacts: 'reports/*', fingerprint: true
      publishHTML(target: [
        allowMissing: true,
        alwaysLinkToLastBuild: true,
        keepAll: true,
        reportDir: 'reports',
        reportFiles: 'demo-report.html',
        reportName: 'Demo Report'
      ])
    }

    success {
      echo "Build, tests, packaging, and report generation completed successfully"
    }

    failure {
      echo "Pipeline failed"
    }
  }
}