pipeline {
  agent { label 'wsl-docker' }

  environment {
    API_IMAGE = 'ghcr.io/amine12344/mlop-test-api'
    FRONTEND_IMAGE = 'ghcr.io/amine12344/mlop-test-frontend'
    DEPLOY_BRANCH = 'feature/test-argo'
    VERSION = "sha-${GIT_COMMIT}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Verify Docker') {
      steps {
        sh '''
          set -eux
          docker version
        '''
      }
    }

    stage('Run tests') {
      steps {
        sh '''
          set +e
          fuser -k 3009/tcp || true
          set -e

          cd app
          npm test
        '''
      }
    }

     stage('API Smoke Tests') {
      steps {
        sh '''
          set -eux
          cd app
          npm install
          npm test
        '''
      }
    }

    stage('Frontend Static Tests') {
      steps {
        sh '''
          set -eux
          ./frontend/test-frontend.sh
        '''
      }
    }

    stage('Build images') {
      steps {
        sh '''
          set -eux
          docker build -t ${API_IMAGE}:${VERSION}_withjenkins ./app
          docker build -t ${FRONTEND_IMAGE}:${VERSION}_withjenkins ./frontend
        '''
      }
    }

     stage('Container Smoke Tests') {
      steps {
        sh '''
          set -eux

          docker network create mlop-test-net || true
          docker rm -f test-api test-frontend >/dev/null 2>&1 || true

          docker run -d --name test-api --network mlop-test-net \
            -e PORT=8080 \
            -e DB_HOST=postgres \
            -e DB_PORT=5432 \
            -e DB_NAME=postgres \
            -e DB_USER=postgres \
            -e DB_PASSWORD=postgres \
            -e APP_VERSION=test-ci \
            -p 18080:8080 \
            ${API_IMAGE}:${VERSION}${TAG_SUFFIX}

          sleep 4
          curl -fsS http://localhost:18080/healthz
          curl -fsS http://localhost:18080/readyz
          curl -fsS http://localhost:18080/ | grep version

          docker run -d --name test-frontend \
            -p 18081:80 \
            ${FRONTEND_IMAGE}:${VERSION}${TAG_SUFFIX}

          sleep 3
          curl -fsS http://localhost:18081/ | grep '<title>'
          curl -fsS http://localhost:18081/app.js | grep 'loadStatus'

          docker rm -f test-api test-frontend
        '''
      }
    }


    stage('Login to GHCR') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'ghrc-creds', usernameVariable: 'GH_USER', passwordVariable: 'GH_PAT')]) {
          sh '''
            echo "$GH_PAT" | docker login ghcr.io -u "$GH_USER" --password-stdin
          '''
        }
      }
    }

    stage('Push images') {
      steps {
        sh '''
          docker push ${API_IMAGE}:${VERSION}_withjenkins
          docker push ${FRONTEND_IMAGE}:${VERSION}_withjenkins
        '''
      }
    }

    stage('Update Helm values') {
      steps {
        sh '''
          yq -i '.api.image.tag = strenv(VERSION)+"_withjenkins"' helm/mlop-test/values.yaml
          yq -i '.frontend.image.tag = strenv(VERSION)+"_withjenkins"' helm/mlop-test/values.yaml
        '''
      }
    }
    stage('Generate Demo Report') {
      steps {
        sh '''
          set -eux

          mkdir -p reports

          cat > reports/report.html <<EOF
          <!doctype html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Jenkins Report mlop test </title>
            <style>
              body { font-family: Arial, sans-serif; margin: 30px; background: #f8fafc; color: #111827; }
              h1 { margin-bottom: 8px; }
              .card { background: white; border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; margin-bottom: 16px; }
              .label { font-weight: bold; color: #374151; }
              code { background: #f3f4f6; padding: 2px 6px; border-radius: 6px; }
            </style>
          </head>
          <body>
            <h1>MLOps Demo Report</h1>
            <p>Generated by Jenkins pipeline</p>

            <div class="card">
              <div><span class="label">Branch:</span> <code>${DEPLOY_BRANCH}</code></div>
              <div><span class="label">Commit:</span> <code>${GIT_COMMIT}</code></div>
              <div><span class="label">Version Tag:</span> <code>${VERSION}${TAG_SUFFIX}</code></div>
              <div><span class="label">Build Number:</span> <code>${BUILD_NUMBER}</code></div>
              <div><span class="label">Build URL:</span> <code>${BUILD_URL}</code></div>
            </div>

            <div class="card">
              <div><span class="label">API Image:</span> <code>${API_IMAGE}:${VERSION}${TAG_SUFFIX}</code></div>
              <div><span class="label">Frontend Image:</span> <code>${FRONTEND_IMAGE}:${VERSION}${TAG_SUFFIX}</code></div>
            </div>

            <div class="card">
              <div><span class="label">Checks included:</span></div>
              <ul>
                <li>API smoke tests</li>
                <li>Frontend static tests</li>
                <li>Helm validation</li>
                <li>Container smoke tests</li>
              </ul>
            </div>
          </body>
          </html>
          EOF
        '''
      }
    }

    stage('Archive Report') {
      steps {
        archiveArtifacts artifacts: 'reports/report.html', fingerprint: true
      }
  }
  post {
  always {
    sh '''
      docker rm -f test-api test-frontend >/dev/null 2>&1 || true
    '''
    archiveArtifacts artifacts: 'reports/*', fingerprint: true
    publishHTML(target: [
      allowMissing: false,
      alwaysLinkToLastBuild: true,
      keepAll: true,
      reportDir: 'reports',
      reportFiles: 'report.html',
      reportName: 'Report'
    ])
  }
  success {
    echo "Build, tests, and packaging completed successfully"
  }
  failure {
    echo "Pipeline failed"
  }
}
}