namespace: mlop-test

api:
  replicaCount: 1
  image:
    repository: ghcr.io/amine12344/mlop-test-api
    tag: sha-4a8ec84
    pullPolicy: Always
  port: 8080
  env:
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: postgres
    DB_USER: postgres

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/amine12344/mlop-test-frontend
    tag: sha-4a8ec84
    pullPolicy: Always
  port: 80

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  port: 5432
  auth:
    user: postgres
    password: postgres
    database: postgres

ingress:
  enabled: true
  className: nginx
  host: mlop.local