namespaceOverride: mlop-test

api:
  replicaCount: 1
  image:
    repository: ghcr.io/amine12344/mlop-test-api
    tag: "sha-latest"
    pullPolicy: IfNotPresent
  containerPort: 8080
  service:
    port: 8080
  env:
    PORT: "8080"
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: mlop
    DB_USER: mlop
    DB_PASSWORD: mlop
    APP_VERSION: "sha-latest"
  probes:
    livenessPath: /healthz
    readinessPath: /readyz

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/amine12344/mlop-test-frontend
    tag: "sha-latest"
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    port: 80
  env:
    FRONTEND_VERSION: "sha-latest"
    API_BASE_URL: "http://api:8080"

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  containerPort: 5432
  service:
    port: 5432
  auth:
    database: mlop
    username: mlop
    password: mlop

ingress:
  enabled: true
  className: nginx
  host: mlop.local