namespace: mlop-test
postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  containerPort: 5432
  auth:
    user: postgres
    password: postgres
    database: postgres
api:
  replicaCount: 1
  image:
    repository: ghcr.io/amine12344/mlop-test-api
    tag: "sha-857b5e7ce221c3568df058055695cec5421cb21d"
    pullPolicy: Always
  service:
    port: 8080
  containerPort: 8080
  env:
    PORT: "8080"
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: postgres
    DB_USER: postgres
    APP_VERSION: "sha-857b5e7ce221c3568df058055695cec5421cb21d"
frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/amine12344/mlop-test-frontend
    tag: "sha-857b5e7ce221c3568df058055695cec5421cb21d"
    pullPolicy: Always
  service:
    port: 80
  containerPort: 80
  env:
    FRONTEND_VERSION: "sha-857b5e7ce221c3568df058055695cec5421cb21d"
ingress:
  enabled: true
  className: nginx
  host: mlop.local
