apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-lab
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-lab
  template:
    metadata:
      labels:
        app: helm-lab
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80