apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlop-test
  namespace: mlop-test
spec:
  ingressClassName: nginx
  rules:
    - host: mlop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80