apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.containerPort }}
          env:
            - name: PORT
              value: {{ .Values.api.env.PORT | quote }}
            - name: DB_HOST
              value: {{ .Values.api.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.api.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.api.env.DB_NAME | quote }}
            - name: DB_USER
              value: {{ .Values.api.env.DB_USER | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.api.env.DB_PASSWORD | quote }}
            - name: APP_VERSION
              value: {{ .Values.api.env.APP_VERSION | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.probes.livenessPath }}
              port: {{ .Values.api.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.probes.readinessPath }}
              port: {{ .Values.api.containerPort }}