apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.api.port | quote }}
  DB_HOST: {{ .Values.api.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.api.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.api.env.DB_NAME | quote }}
  DB_USER: {{ .Values.api.env.DB_USER | quote }}