events {}

http {
  upstream api_upstream {
    server api:8084;
  }

  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }

    location /api/ {
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://api_upstream;
    }

    location /health {
      proxy_pass http://api_upstream/health;
    }

    location /healthz {
      proxy_pass http://api_upstream/healthz;
    }

    location /readyz {
      proxy_pass http://api_upstream/readyz;
    }

    location /db {
      proxy_pass http://api_upstream/db;
    }

    location /predict {
      proxy_pass http://api_upstream/predict;
      proxy_set_header Content-Type application/json;
    }
  }
}