apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlop-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amine12344/mlop-test.git
    targetRevision: feature/kind-kube
    path: helm/mlop-test
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mlop-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true