controller:
  admin:
    username: admin
    password: mlops1234

  serviceType: ClusterIP

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - docker-workflow

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

agent:
  enabled: true