name: Auto Release + Update Helm

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_API: mlop-test-api
  IMAGE_FRONTEND: mlop-test-frontend
  BRANCH: feature/test-argo

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # API
      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mlop-test-api:${{ env.VERSION }}

      # FRONTEND
      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mlop-test-frontend:${{ env.VERSION }}

  update-helm:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v4
        with:
          ref: feature/test-argo

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install yq
        run: sudo snap install yq

      - name: Update Helm values
        run: |
          yq -i '.api.image.tag = strenv(VERSION)' helm/mlop-test/values.yaml
          yq -i '.frontend.image.tag = strenv(VERSION)' helm/mlop-test/values.yaml
          yq -i '.api.env.APP_VERSION = strenv(VERSION)' helm/mlop-test/values.yaml
          yq -i '.frontend.env.FRONTEND_VERSION = strenv(VERSION)' helm/mlop-test/values.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/mlop-test/values.yaml
          git commit -m "release: $VERSION" || exit 0
          git push origin feature/test-argo